### ISSUE TITLE
Enhanced scan logic

### ISSUE THREAD

**Issue by lukeswitz** [lukeswitz/AtomGPS_wigler#11]
**What**: Weight some channels with a longer dwell time. 

**Why**: Spending equal time per channel could be optimized. 

**How**: Wrap it in a `for` loop, use longer time params for popular channels. Input on said channels welcome

**Comment by pejacoby** [comment]
I need to do some more side-by-side comparisons, but here's a 2.5 hour drive comparison in my area running the AtomGPS alongside a DNSDriveBy and a Jhewitt rig.
Obviously channels 1, 6, and 11 are the hotspots note the mid-way point peaks on 3 and 9. 

<img width="781" alt="Screenshot 2024-01-06 at 8 19 42 AM" src="https://github.com/lukeswitz/AtomGPS_wigler/assets/16978661/8928bd0d-f009-4004-9d2e-7d4487eefebc">

**Comment by lukeswitz** [comment]
Well that’s about as helpful as it gets for a visual! Interesting you didn’t see any on 14, I get a ton of new cameras on that end. Optimization commence!

**Comment by pejacoby** [comment]
I should've posted the underlying data -- there are some on 14 they just get squished out.
<img width="179" alt="Screenshot 2024-01-06 at 10 27 43 AM" src="https://github.com/lukeswitz/AtomGPS_wigler/assets/16978661/18207183-354a-4064-89ef-49f6049234d9">

**Comment by pejacoby** [comment]
Also interesting - just did a shorter suburban drive with 3 Atoms and the WiSpy and saw NO hosts on channel 12 or 14. Those appear to be rarer in my area, so perhaps they warrant watching for as less common outliers.

**Comment by lukeswitz** [comment]
Closing until more data available
