### ISSUE TITLE
-1 pin assignment causing errors

### ISSUE THREAD

**Issue by lukeswitz** [lukeswitz/AtomGPS_wigler#12]
Serial flooding with `gpio: gpio_set_level(227): GPIO output gpio_num error` 

See issue with esp32 board package: https://github.com/espressif/arduino-esp32/issues/6737

**Comment by lukeswitz** [comment]
(`-1, SPI, 40000000)` defining ss pin here is unnecessary as pointed out by @birukun and fixes the errors for gpio

**Comment by pejacoby** [comment]
No more GPIO errors on my unit!
![Screen Shot 2024-01-09 at 5 23 35 PM](https://github.com/lukeswitz/AtomGPS_wigler/assets/16978661/7e01ddbd-3190-43df-b096-f56b98d9a747)

**Comment by lukeswitz** [comment]
Reverted the commit, the gpio garb is back. Seems maybe ESP32-PICO-D4 pins might be helpful from the docs, as that's the chip it'll detect. Either can be used in IDE with the same results. Waiting on @birukun for his SPI fix he messaged me about.

**Comment by lukeswitz** [comment]
closing, dupe of #17
