### ISSUE TITLE
SD Card not recognized on start / SD.begin parameters

### ISSUE THREAD

**Issue by birukun** [lukeswitz/AtomGPS_wigler#17]
Latest version doesn't see my SD Card unless I specify parameters for SD.begin()

while (!SD.begin(-1, SPI, 40000000))

This works but has not solved the gpio_num issue for me yet. I tested my SD Card successfully using the example code for SD.h.

I am simply copying the code into my Arduino IDE so I may have different libraries or something when compiling. I wanted to mention it in case others have the same issue. 
Thanks

**Comment by lukeswitz** [comment]
Can you clarify how you commented out SPI entirely without issue? I can’t seem to replicate that

**Comment by CorruptedPixl** [comment]
I'm also having issues using a 32GB card. I've heard these have been used successfully before so I'm not sure what's up.
I tried formatted as FAT32 and ExFAT, neither seem to work.

**Comment by lukeswitz** [comment]
This is interesting. Can you both verify you’re using the new flashing command and the compiled binary?

**Comment by lukeswitz** [comment]
> I'm also having issues using a 32GB card. I've heard these have been used successfully before so I'm not sure what's up. I tried formatted as FAT32 and ExFAT, neither seem to work.

Did you use the card in previous builds with success? I believe it is only supposed to support 4 but people have told me some 32s worked fine. I personally use microcenter 16 cheapies with no problems

**Comment by pejacoby** [comment]
I have run successfully with a 32GB Lexar E-series card and a SanDisk Ultra.  However, I do detect some performance penalty with the bigger card, so I moved back to 4GB cards. Currently using cheap Cloudisk units from Amazon.

**Comment by lukeswitz** [comment]
Nice catch! I had to format fresh cards to FAT32 with a master boot record. Please let me know if it persists. Cheers

### Windows
1. **Connect SD card**.
2. **Open 'Disk Management'**.
3. **Right-click SD card**, choose '**Format**'.
4. **Select 'FAT32'** and '**Master Boot Record (MBR)**'.
5. **Format**.

### macOS
1. **Insert SD card**.
2. **Open 'Disk Utility'**.
3. **Select SD card**, click '**Erase**'.
4. **Choose 'MS-DOS (FAT)'** and '**Master Boot Record**'.
5. **Erase**.

### Linux
1. **Insert SD card**.
2. **In Terminal**, identify SD card with `lsblk`.
3. **Unmount** with `sudo umount /dev/sdX`.
4. **Format** with `sudo mkfs.vfat /dev/sdXX` (replace `/dev/sdXX` with your card name).

**Comment by CorruptedPixl** [comment]
Just tested again with a freshly formatted 32GB SanDisk Ultra A1 class (red and gray kind) card I had laying around formatted to FAT32, and using esptool to flash v1.3.1 on it.
Still failing to initialize on both units I got, however on one unit the leds don't seem to work either, so that might be more a hardware issue.
I'll see if I can find some 16GB or smaller cards in the coming days to test with

**Comment by lukeswitz** [comment]
> I'll see if I can find some 16GB or smaller cards in the coming days to test with

Those didn’t work for me either. Sandisk is weird like that, their cheap discontinued ones work fine though

**Comment by CorruptedPixl** [comment]
Just did some more testing on that SanDisk card, no luck sadly.
Partitioned into 2x 16GB and 8x 4GB partitions but both don't seem to work.
What brands did you test with for the 16GB cards? Might just order one of those.

**Comment by lukeswitz** [comment]
Shucks @CorruptedPixl that’s indeed no fun. Before spending money, have you tried as @birukun said and reverted that line? If still no go, I will get a list I know to work together. Microcenter 16GB 5packs are my goto.

**Comment by pejacoby** [comment]
I checked the format on my Lexar 32GB card - FAT32 with MBR, same as my cheapo 4GB Cloudisk card..
I'll grab some part #'s for my various cards later

**Comment by CorruptedPixl** [comment]
I added the parameters but still no luck. I also see the gpio_num error when compiling via the Arduino IDE.
I double checked and that message is not present when flashing the latest binary.

**Comment by birukun** [comment]
After I added parameters to the SD.begin() function, it ran for 4 hours straight without any issues. This was at my desk so not the real world load. I am using Patriot 16GB SDHC Class 10 cheapo cards.  
Will try a run outside soon. Sorry I have been delayed in answering, work is nuts.

**Comment by lukeswitz** [comment]
> After I added parameters to the SD.begin() function, it ran for 4 hours straight without any issues. This was at my desk so not the real world load. I am using Patriot 16GB SDHC Class 10 cheapo cards. It did show the gpio_num errors but just kept counting up with no impact that I could tell. Will try a run outside soon. Sorry I have been delayed in answering, work is nuts.

 Confused, you said to comment out SPI and it works for you. This is not the case? Elaborate when you have the time it would be useful thanks. Is it the same card you’ve been using without failure?

**Comment by lukeswitz** [comment]
This is very widespread, so the best thing to do for now is revert the commit and not worry so much about the serial garbage. Those are warnings that have no measurable impact on performance in testing. Waiting on that code without SPI as @birukun told me he uses....

**Comment by lukeswitz** [comment]
`uint32_t frequency = 4000000` - id bet those having issues didn't flash using the esptool command.
params `uint8_t ssPin = SS, SPIClass & spi = SPI, uint32_t frequency = 4000000, const char * mountpoint = "/sd", uint8_t max_files = 5, bool format_if_empty = false`

**Comment by lukeswitz** [comment]
When using -1 we don't assign a pin and that bothers FastLED. 
`No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ `

Not a major issue but absolutely worth fixing

**Comment by CorruptedPixl** [comment]
> `uint32_t frequency = 4000000` - id bet those having issues didn't flash using the esptool command.
> params `uint8_t ssPin = SS, SPIClass & spi = SPI, uint32_t frequency = 4000000, const char * mountpoint = "/sd", uint8_t max_files = 5, bool format_if_empty = false`

Can confirm this is what I'm seeing as well. When using the Arduino IDE I get the serial spam, when manually flashing the binary with esptool and the params, I don't.

**Comment by lukeswitz** [comment]
@CorruptedPixl same, but it seems a lot of others are having problems so for now it's back in the codebase. v1.3.1 will still be there for those who want the "fix". Thanks for testing that

**Comment by birukun** [comment]
> > `uint32_t frequency = 4000000` - id bet those having issues didn't flash using the esptool command.
> > params `uint8_t ssPin = SS, SPIClass & spi = SPI, uint32_t frequency = 4000000, const char * mountpoint = "/sd", uint8_t max_files = 5, bool format_if_empty = false`
> 
> Can confirm this is what I'm seeing as well. When using the Arduino IDE I get the serial spam, when manually flashing the binary with esptool and the params, I don't.

I believe this is my issue - I used the Arduino IDE that in turn uses esptool but without all the switches. 

@lukeswitz your new code is fine as long as the flash is done using the command line esptool with the switches for SPI built in. I will use the esptool command line as you specified.

**Comment by pejacoby** [comment]
Interesting -- I've been doing all my flashing of late from the MacOS Arduino IDE and had no issues.  It even uses a slight older version of esptool (4.5.1 I believe versus my 4.6.1 command line) and I've had no issues.

**Comment by lukeswitz** [comment]
Thanks all, @birukun do you suggest leaving the 1.3.1 as latest release with 1.3.2 as a prerelease? Let me know what the move is here that helps the most. It’s been a confusing couple of hours any help appreciated!

**Comment by birukun** [comment]
> `uint32_t frequency = 4000000` - id bet those having issues didn't flash using the esptool command. params `uint8_t ssPin = SS, SPIClass & spi = SPI, uint32_t frequency = 4000000, const char * mountpoint = "/sd", uint8_t max_files = 5, bool format_if_empty = false`

Where do I specify these parameters? I don't see in the esptool docs how to add these. 

I flashed the binary release you created for 1.3.2 and it works albeit the gpio_num errors persist but as you mentioned it is not impacting performance. We can close this as I am pretty sure the issue is on my end using Arduino IDE to flash.

**Comment by lukeswitz** [comment]
> >
> Where do I specify these parameters? I don't see in the esptool docs how to add these.
> 

Those are specified for SD.Begin() in the [SD library](https://reference.arduino.cc/reference/en/libraries/sd/begin/)

**Comment by birukun** [comment]
OK I got my wires crossed. Thank you

**Comment by hmax42** [comment]
if we use SD.begin() withput parameters
SS is used as default which is 19, which is used already as MOSI
if -1 is used, the esp-idf throws an error in the serial out, but it works
i use pin 15, it's unused. and gives no error

**Comment by lukeswitz** [comment]
Will definitely try this. Been an issue from the jump. Appreciate that pin assignment

**Comment by lukeswitz** [comment]
> if we use SD.begin() withput parameters SS is used as default which is 19, which is used already as MOSI if -1 is used, the esp-idf throws an error in the serial out, but it works i use pin 15, it's unused. and gives no error

And this works perfectly.. 
![4EE4660A-5B7A-44CE-8EDA-92118AF44B73](https://github.com/lukeswitz/AtomGPS_wigler/assets/10099969/a541dbd9-2865-4b41-b6da-a65bf425c56b)

**Comment by hmax42** [comment]
pin assignments vary dependeing on the specific board used
i use m5atom and there i found it
i guess if someone is using generic esp32 as board, the pin assigned is something different which may not conflict

**Comment by lukeswitz** [comment]
Fixed by 

> pin assignments vary dependeing on the specific board setting used i use m5atom and there i found it i guess if someone is using generic esp32 as board, the pin assigned is something different which may not conflict

Nice work. It was using the -1 as an unassigned pin from what I understand. This solves the problem thanks
