### ISSUE TITLE
Scan interval too small

### ISSUE THREAD

**Issue by lukeswitz** [lukeswitz/AtomGPS_wigler#18]
A happy medium of 300-600ms should be enough. Input welcome on this for sure.

**Comment by pejacoby** [comment]
Are you referring to the 200-400ms range used in the adaptive code?  When standing still with the 1.3.1 build I picked up 15-20 more APs with the default settings than I had with the previous build.  Not sure how to gauge the timing from a longer run.  Any thoughts on how to hone in on optimal?

**Comment by lukeswitz** [comment]
I was thinking a delay in between not the durations. Running without delay may give a lot of empty lines- with a small delay 150ms it seems to work consistently. Nice drive btw. What are your thoughts? Scan continuously or with a delay?

**Comment by lukeswitz** [comment]
Closing for now, going to test a few different rates and report back. Will test: 0,150,250,500 for yield:blanks ratio.
