### ISSUE TITLE
model value for Wigle file is "GPS Kit" in header, "gps" on stats page on wigle.net

### ISSUE THREAD

**Issue by pejacoby** [lukeswitz/AtomGPS_wigler#20]
Currently the "model" value in the Wigle CSV header is "model=GPS Kit".

The CSV spec doesn't indicate how spaces in the values are handled, but the Stats output make it look like the value is being truncated to "gps".
![Wigle stats - GPS](https://github.com/lukeswitz/AtomGPS_wigler/assets/16978661/caef8360-402f-4d05-b6ac-b1cfa229c75f)

Should the code be updated to "GPS-Kit" or "AtomGPS"?  Do we pick a value or keep it generic to group the AtomGPS, AtomMatrix, etc M5Stack models together?

CSV spec - https://api.wigle.net/csvFormat.html
Stats page - https://wigle.net/stats#octetstats

**Comment by lukeswitz** [comment]
Spaces are handled as spaces so far as I can tell from others. 
![IMG_0309](https://github.com/lukeswitz/AtomGPS_wigler/assets/10099969/50e08d70-ba88-4e33-802b-17fec4f81fa9)
