### ISSUE TITLE
How expensive is file open/close? Could we batch data writes?

### ISSUE THREAD

**Issue by pejacoby** [lukeswitz/AtomGPS_wigler#21]
Was looking at speed opportunities in the scan loop and I'm wondering how expensive the file open/write/close cycle is in logData()?  Currently logData() is called inside the main scan loop once for each network found on each channel.

Could we collect all the networks seen for a channel, or even for a full cycle through all channels, into an array and pass that to logData() for one big open/write all/close per cycle, instead of individual writes?  It would trade memory for open/close calls.

**Comment by lukeswitz** [comment]
It's not cheap for SD card life, but the tradeoff is stability. If the unit is powered off before the file's closed it'll often be corrupted. Other ways I've tried: circular caching the data to be written then incrementally writing to the file. If you can find some time to code out improvements that'd be great.

**Comment by pejacoby** [comment]
I have a first pass total hack that I need to test out. Not sure if I have the skills to do a proper ring-buffer but I'll poke at it a bit.  Point taken on stability, we'd loose the last cached but not written set of APs on power off.  I have yet to kill an SD card in any unit yet, so it might be not net significant value.  We'll see!

**Comment by lukeswitz** [comment]
> we'd loose the last cached but not written set of APs on power off.

It will leave you with nothing if the file isn’t closed, but I might have missed something in tests. A good reference point would be looking at how others like Hewitt handle it and work from there. No need to waste time reinventing what works. Cheers
