### ISSUE TITLE
To Channel 14 or Not to Channel 14?

### ISSUE THREAD

**Issue by pejacoby** [lukeswitz/AtomGPS_wigler#22]
I noticed in 1.5 you dropped scanning of channel 14. This aligns with JHewitt's code.  I haven't been able to locate the equivalent code in WigleWiFi yet.

I know it's an illegal channel in the US, but curiously I have a fair number of hits on it in my drive files -- 2,077 hits across a collection of files.  I'm doing some forensics to see what's out there. So far it's look like NVRs and cheap IOT devices.

The count on 14 is minimal compared to 301,506 hits on channel 11; 443,801 hits on channel 6; and 492,818 hits on channel 1.
The Low power channels 12 and 13 have 201 and 265 hits, respectively.

Is it naughty to LISTEN on Channel 14 in the US?  Interesting to see this anomalous use out there, small as it is.

**Comment by lukeswitz** [comment]
It’s commented to change to your region. Gonna leave it like this for now but thanks for pointing things like this out.

**Comment by lukeswitz** [comment]
Makes a good argument for a “sniffer” version. It would look for anomalies among the baseline… suspect MACs etc.

**Comment by pejacoby** [comment]
Agree, there's something out there chattering, it's not supposed to be, but there it is. Looking around the Wigle map specifically in places I've never been there are quite a few of these "NVR9ca3axxxxxxx" and "NVR083a2xxxxxxx" SSIDs running on Channel 14 -- the most common names I've seen.  Various other variations, with many more running on legit channels 1-13.

**Comment by lukeswitz** [comment]
Absolutely. I think it’s meaningful to capture all channels. Leaving that task to something with reach (trace is super weak on the Atom) is the move if recon is the goal. Recon branch ftw.
