### ISSUE TITLE
gpio_set_level(227): GPIO output gpio_num error in serial output?

### ISSUE THREAD

**Issue by pejacoby** [lukeswitz/AtomGPS_wigler#5]
Getting a ton of errors in serial output 

StartM5Atom initializing...OK
E (63) gpio: gpio_set_level(227): GPIO output gpio_num error

They pause when we wait for the GPS fix, then resume in bursts of dozens per second before and after a new filename is created.

10:46:35.052 -> E (223) gpio: gpio_set_level(227): GPIO output gpio_num error
10:46:35.052 -> E (228) gpio: gpio_set_level(227): GPIO output gpio_num error
10:46:35.084 -> E (234) gpio: gpio_set_level(227): GPIO output gpio_num error

Looks like this is a known thing -- https://github.com/espressif/arduino-esp32/issues/6737 -- but doesn't have a direct solution.

Curious if others are seeing it.  Makes debugging via serial output really a pain.

**Comment by lukeswitz** [comment]
I was told this is from the -1 used by lozaning :

“I think all that code may actually work just fine, but the usage of -1 in the serial and SPI initiations makes the newest expressif Arduino Core barf a bunch of gpio errors over serial.”

I’ll need to read more on this. Refactoring this before it becomes spaghetti is next. Then to optimize and fix a bunch.

**Comment by lukeswitz** [comment]
Reopening after a little test. Could you do me a favor? When flashing next time, choose 'DIO' instead of 'QIO' and let me know if you still see those. Another alternative people mention is flashing at a frequency of 40 instead of 80.

**Comment by pejacoby** [comment]
I changed to DIO mode and left 80MHz  and saw this "bitbanged output" error during the compile.  I'd seen it when I first got things flashed but hadn't been able to recreate it.

In file included from /Users/pejacoby/Documents/Arduino/libraries/FastLED/src/FastLED.h:75,
                 from /Users/pejacoby/Documents/Arduino/libraries/M5Atom/src/utility/LED_DisPlay.h:4,
                 from /Users/pejacoby/Documents/Arduino/libraries/M5Atom/src/utility/LED_DisPlay.cpp:1:
/Users/pejacoby/Documents/Arduino/libraries/FastLED/src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

After the flash I get this start -- still get several dozen gpio errors before reaching the SD card and other initializations.

10:06:56.589 -> ets Jun  8 2016 00:22:57
10:06:56.589 -> 
10:06:56.589 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
10:06:56.589 -> configsip: 188777542, SPIWP:0xee
10:06:56.589 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
10:06:56.589 -> mode:DIO, clock div:1
10:06:56.589 -> load:0x3fff0030,len:1184
10:06:56.589 -> load:0x40078000,len:13260
10:06:56.623 -> load:0x40080400,len:3028
10:06:56.623 -> entry 0x400805e4
10:06:56.919 -> StartM5Atom initializing...OK
10:06:56.952 -> E (65) gpio: gpio_set_level(227): GPIO output gpio_num error
{more of the same}
10:06:57.145 -> E (235) gpio: gpio_set_level(227): GPIO output gpio_num error
10:06:57.145 -> SD Card initialized.
10:06:57.310 -> WiFi initialized.
10:06:57.311 -> GPS Serial initialized.
10:06:57.311 -> Waiting for GPS fix...


Switched to DIO, 40MHz, and flashed again.  Got the same "bitbanged output" message during compile.

In file included from /Users/pejacoby/Documents/Arduino/libraries/FastLED/src/FastLED.h:75,
                 from /Users/pejacoby/Documents/Arduino/libraries/M5Atom/src/utility/LED_DisPlay.h:4,
                 from /Users/pejacoby/Documents/Arduino/libraries/M5Atom/src/utility/LED_DisPlay.cpp:1:
/Users/pejacoby/Documents/Arduino/libraries/FastLED/src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The run process and messages are the same, only minor difference is in the last line here - 'clock div: 2'

10:11:12.971 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
10:11:12.971 -> configsip: 188777542, SPIWP:0xee
10:11:12.971 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
10:11:12.971 -> mode:DIO, clock div:2


Then the same gpio errors again.

**Comment by lukeswitz** [comment]
Is erase flash contents set to yes in Arduino?

**Comment by pejacoby** [comment]
Yep
![Arduino board settings](https://github.com/lukeswitz/AtomGPS_wigler/assets/16978661/9faa84ca-647d-441e-9f1d-fcfde874bc80)

**Comment by lukeswitz** [comment]
Only thing I have different is 80mhz flash frequency and no errors. More investigation needed but maybe a flashing issue with the boot partition

**Comment by pejacoby** [comment]
Tried again with 80MHz, DIO mode, still seeing errors.  Not a huge thing, just make debugging harder.  I've got two more Atoms on the way so I can see if this is a sample size of "1" thing.

10:59:09.115 -> mode:DIO, clock div:1

**Comment by lukeswitz** [comment]
Previously resolved: fixed in 0fa4c45
