### ISSUE TITLE
WIFI_AUTH_WPA2_ENTERPRISE enumeration label difference from JHewitt

### ISSUE THREAD

**Issue by pejacoby** [lukeswitz/AtomGPS_wigler#6]
I noticed there is a difference in AUTH_TYPE list versus JHewitt code. Should we align?

- Jhewitt uses:
    case WIFI_AUTH_WPA2_ENTERPRISE:
      authtype = "[WPA2]";

- AtomGPS uses:
    case WIFI_AUTH_WPA2_ENTERPRISE:
      return "[WPA2_ENTERPRISE]";

The ESP32 spec doesn't give a name for this particular value, just showing
  enumerator WIFI_AUTH_WPA2_ENTERPRISE
  authenticate mode : WiFi EAP security

 https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html

Not sure if Wigle cares for their statistics - they point from the CSV format file to https://developer.android.com/reference/android/net/wifi/ScanResult#capabilities - which doesn't have any direct match-up information in the getSecurityTypes() routine doc.

**Comment by lukeswitz** [comment]
I haven’t seen people doing it the exact same way but I’ll contact someone about standards. Closing as duplicate
