### ISSUE TITLE
Some WiFi AuthType entries in ESP32 doc aren't included

### ISSUE THREAD

**Issue by pejacoby** [lukeswitz/AtomGPS_wigler#7]
General observation - there are a number of WiFi AuthType values in the ESP32 docs that aren't in the code enumeration.
   https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html)

Are all the types from <wifi.h> included in the code? Should they be?
Maybe not relevant if they aren't supported by the chipset?

I do not see this one in JHewitt's code either:

enumerator WIFI_AUTH_ENTERPRISE
authenticate mode : WiFi EAP security

He just has the WPA2 equivalent:
     case WIFI_AUTH_WPA2_ENTERPRISE:
       authtype = "[WPA2]";

**Comment by lukeswitz** [comment]
Good catch. I blame myself for using the code from the lynd wardriver. Though I’m not sure the impact of such things, I’d think it best to follow in the footsteps of Hewitt on these matters.
